### ISSUE TITLE
poetry install error.

### ISSUE THREAD

**Issue by magicianaos** [dfint/df-gettext-toolkit#7] opened 2022-12-16 11:03 UTC
![image](https://user-images.githubusercontent.com/6631032/208084214-7e96bad7-0872-4284-bbc6-66b7d0fdf8f4.png)

As shown in the picture above, 'SNAPSHOT' is not properly installed.
I installed 'PYTHON', downloaded the full version of df-gettext-toolkit, and executed the command below in that folder.

pip install poetry
poetry install

Then the above error message is output.
Please tell me if I have installed PYTHON incorrectly.

**Comment by insolor** [comment] 2022-12-16 11:19
I had a similar problem with the latest version of poetry. Installation of an older version has helped. I don't remember which version I used exactly, probably 1.2.1, so try `pip install -U poetry==1.2.1`

**Comment by insolor** [comment] 2022-12-16 11:45
Well, I found that [python-base](https://github.com/kryzthov/python-base) dependency causes this problem. I'll try to fix this to not depend on old versions of poetry.

**Comment by magicianaos** [comment] 2022-12-16 11:46
> Well, I found that [python-base](https://github.com/kryzthov/python-base) dependency causes this problem. I'll try to fix this to not depend on old versions of poetry.

Thanks :)

**Comment by insolor** [comment] 2022-12-16 15:43
@magicianaos should be fixed now. Please, try to download again and install

**Comment by magicianaos** [comment] 2022-12-16 20:14
> @magicianaos the problem should be fixed now. Please, try to download again and install

Thanks

**Comment by insolor** [comment] 2022-12-17 10:00
@magicianaos I assume that the problem is gone, so I'm closing the issue.

**Closed by insolor** 2022-12-17 10:00 UTC
Labels: bug
